version: "3.9"
services: 
    gateway: 
        build: .
        image: hesoyam/gateway:latest
        container_name: gateway
        restart: on-failure
        ports:
            - ${GATEWAY_PORT}:9090
        environment: 
            ADVERTISEMENT_HOST: advertisement 
            ADVERTISEMENT_PORT: ${ADVERTISEMENT_PORT}
            CONTENT_HOST: content
            CONTENT_PORT: ${CONTENT_PORT}
            LOCATION_HOST: location
            LOCATION_PORT: ${LOCATION_PORT}
            MESSAGING_HOST: messaging
            MESSAGING_PORT: ${MESSAGING_PORT}
            USERS_HOST: users
            USERS_PORT: ${USERS_PORT}
    advertisement:
        build: ../Advertisement
        image: hesoyam/advertisement:latest
        container_name: advertisement
        restart: on-failure
        ports:
            - ${ADVERTISEMENT_PORT}:9091
        environment: 
            DB_PORT: ${ADVERTISEMENT_DB_PORT}
            DB_HOST: advertisementdb
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            DB_NAME: ${ADVERTISEMENT_DB_NAME}
        depends_on: 
            - advertisementdb
    advertisementdb:
        image: postgres:13.3-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${ADVERTISEMENT_DB_NAME}
        ports: 
            - ${ADVERTISEMENT_DB_PORT}:5432
        volumes:
            - advertisement-db:/var/lib/postgresql/data
    content:
        build: ../Content
        image: hesoyam/content:latest
        container_name: content
        restart: on-failure
        ports:
            - ${CONTENT_PORT}:9092
        environment: 
            DB_PORT: ${CONTENT_DB_PORT}
            DB_HOST: contentdb
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            DB_NAME: ${CONTENT_DB_NAME}
        depends_on: 
            - contentdb
    contentdb:
        image: postgres:13.3-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${CONTENT_DB_NAME}
        ports: 
            - ${CONTENT_DB_PORT}:5432
        volumes:
            - content-db:/var/lib/postgresql/data
    location:
        build: ../Location
        image: hesoyam/location:latest
        container_name: location
        restart: on-failure
        ports:
            - ${LOCATION_PORT}:9093
        environment: 
            DB_PORT: ${LOCATION_DB_PORT}
            DB_HOST: locationdb
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            DB_NAME: ${LOCATION_DB_NAME}
        depends_on: 
            - locationdb
    locationdb:
        image: postgres:13.3-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${LOCATION_DB_NAME}
        ports: 
            - ${LOCATION_DB_PORT}:5432
        volumes:
            - location-db:/var/lib/postgresql/data
    messaging:
        build: ../Messaging
        image: hesoyam/messaging:latest
        container_name: messaging
        restart: on-failure
        ports:
            - ${MESSAGING_PORT}:9094
        environment: 
            DB_PORT: ${MESSAGING_DB_PORT}
            DB_HOST: messagingdb
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            DB_NAME: ${MESSAGING_DB_NAME}
        depends_on: 
            - messagingdb
    messagingdb:
        image: postgres:13.3-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${MESSAGING_DB_NAME}
        ports: 
            - ${MESSAGING_DB_PORT}:5432
        volumes:
            - messaging-db:/var/lib/postgresql/data
    users:
        build: ../Users
        image: hesoyam/users:latest
        container_name: users
        restart: on-failure
        ports:
            - ${USERS_PORT}:9095
        environment: 
            DB_PORT: ${USERS_DB_PORT}
            DB_HOST: usersdb
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            DB_NAME: ${USERS_DB_NAME}
            JWT_SECRET: 12345
            JWT_TOKEN_LIFE_LENGTH: 24
        depends_on: 
            - usersdb
    usersdb:
        image: postgres:13.3-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${USERS_DB_NAME}
        ports: 
            - ${USERS_DB_PORT}:5432
        volumes:
            - users-db:/var/lib/postgresql/data
    webshop:
        build: ../WebShop
        image: hesoyam/webshop:latest
        container_name: webshop
        restart: on-failure
        ports:
            - ${WEBSHOP_PORT}:9096
        environment: 
            DB_PORT: ${WEBSHOP_DB_PORT}
            DB_HOST: webshopdb
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            DB_NAME: ${WEBSHOP_DB_NAME}
        depends_on: 
            - webshopdb
    webshopdb:
        image: postgres:13.3-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${WEBSHOP_DB_NAME}
        ports: 
            - ${WEBSHOP_DB_PORT}:5432
        volumes:
            - webshop-db:/var/lib/postgresql/data
volumes: 
    advertisement-db:
    content-db:
    location-db:
    messaging-db:
    users-db:
    webshop-db:

    